# Generated by Django 5.0.6 on 2026-07-03 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_id", models.CharField(max_length=20, unique=True)),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("GENERAL", "General Practice"),
                            ("PEDIATRICS", "Pediatrics"),
                            ("SURGERY", "Surgery"),
                            ("CARDIOLOGY", "Cardiology"),
                            ("EMERGENCY", "Emergency"),
                            ("NURSING", "Nursing"),
                            ("ADMIN", "Administration"),
                        ],
                        default="GENERAL",
                        max_length=20,
                    ),
                ),
                ("specialization", models.CharField(blank=True, max_length=150)),
                ("designation", models.CharField(blank=True, max_length=100)),
                ("date_joined", models.DateField(auto_now_add=True)),
                ("is_available", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["employee_id"],
            },
        ),
        migrations.CreateModel(
            name="Shift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("GENERAL", "General Practice"),
                            ("PEDIATRICS", "Pediatrics"),
                            ("SURGERY", "Surgery"),
                            ("CARDIOLOGY", "Cardiology"),
                            ("EMERGENCY", "Emergency"),
                            ("NURSING", "Nursing"),
                            ("ADMIN", "Administration"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("COMPLETED", "Completed"),
                            ("MISSED", "Missed"),
                        ],
                        default="SCHEDULED",
                        max_length=12,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shifts",
                        to="staff_management.staffprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "start_time"],
            },
        ),
    ]
